<?php
return [
    'sections' => [
        [
            'id' => 'basic',
            'title' => 'Základné údaje',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'diagnosis', 'label' => 'Lekárska diagnóza'],
                ['id' => 'recommendedPharmacy', 'label' => 'Odporučená farmakoterapia'],
                ['id' => 'admissionDate', 'label' => 'Dátum prijatia do starostlivosti'],
            ],
        ],
        [
            'id' => 'allergies',
            'title' => 'Alergie',
            'layout' => 'full',
            'fields' => [
                ['id' => 'allergies', 'label' => 'Alergie'],
                ['id' => 'allergies.otherFindings', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'abuses',
            'title' => 'Abúzy',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'abuses', 'label' => 'Abúzy'],
            ],
        ],
        [
            'id' => 'family',
            'title' => 'Rodinná anamnéza',
            'layout' => 'full',
            'fields' => [
                ['id' => 'familyAnamnesis', 'label' => 'Rodinná anamnéza'],
                ['id' => 'familyAnamnesis.otherFindings', 'label' => 'Poznámka'],
            ],
        ],
        [
            'id' => 'social',
            'title' => 'Sociálna anamnéza',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'employment', 'label' => 'Povolanie'],
                ['id' => 'socialConditions', 'label' => 'Sociálne podmienky'],
                ['id' => 'socialConditions.otherFindings', 'label' => 'Iné zistenia'],
                ['id' => 'socialStatus', 'label' => 'Sociálny stav'],
                ['id' => 'socialContacts', 'label' => 'Sociálne kontakty'],
                ['id' => 'supportSystems', 'label' => 'Systémy podpory'],
                ['id' => 'socialCulture', 'label' => 'Kultúra a sociálne faktory'],
                ['id' => 'socialMedia', 'label' => 'Sociálne médiá'],
            ],
        ],
        [
            'id' => 'healthPerception',
            'title' => 'Vnímanie zdravia',
            'layout' => 'full',
            'fields' => [
                ['id' => 'healthPerception.description', 'label' => 'Subjektívny popis ťažkostí pacienta'],
            ],
        ],
        [
            'id' => 'consciousnessOrientation',
            'title' => 'Vedomie a orientácia',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'consciousness', 'label' => 'Vedomie'],
                ['id' => 'consciousnessOtherNotes', 'label' => 'Iné zistenia'],
                ['id' => 'orientation', 'label' => 'Orientácia'],
                ['id' => 'orientationOtherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'nursingAssessment',
            'title' => 'Vstupný záznam sesterského posúdenia zdravotného stavu pacienta',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'nursing.caredRecommendedBy', 'label' => 'Starostlivosť odporúčaná'],
                ['id' => 'nursing.otherDoctor', 'label' => 'Iný ošetrujúci lekár'],
                ['id' => 'nursing.otherDoctorDetails', 'label' => 'Aký'],
                ['id' => 'nursing.transferredFromOtherFacility', 'label' => 'Prevzatý z iného zariadenia'],
                ['id' => 'nursing.transferredFromOtherFacilityDetails', 'label' => 'Odkiaľ'],
                ['id' => 'nursing.department', 'label' => 'Oddelenie'],
                ['id' => 'nursing.lastHospitalizationFrom', 'label' => 'Posledná hospitalizácia od'],
                ['id' => 'nursing.lastHospitalizationTo', 'label' => 'do'],
            ],
        ],
        [
            'id' => 'circulation',
            'title' => 'Cirkulácia',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'bloodPressure', 'label' => 'TK (mmHg)'],
                ['id' => 'temperature', 'label' => 'TT (°C)'],
                ['id' => 'pulse', 'label' => 'P (/min)'],
                ['id' => 'circulation.problemExists', 'label' => 'Cirkulácia – pobem'],
                ['id' => 'hypotensionHypertension', 'label' => 'Hypotenzita/Hypertenzita'],
                ['id' => 'irregularPulse', 'label' => 'Nepravidelný pulz'],
                ['id' => 'circulation.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'breathing',
            'title' => 'Dýchanie',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'respiratoryRate', 'label' => 'D (/min)'],
                ['id' => 'breathing.problemExists', 'label' => 'Dýchanie – pobem'],
                ['id' => 'irregularities', 'label' => 'Nepravidelnosti'],
                ['id' => 'breathing.otherNotes', 'label' => 'Iné zistenia'],
                ['id' => 'suctioning', 'label' => 'Odsávanie'],
                ['id' => 'oxygenTherapy', 'label' => 'Kyslíková terapia'],
                ['id' => 'mechanicalVentilation', 'label' => 'Mechanická ventilácia'],
                ['id' => 'inhalation', 'label' => 'Inhalácia'],
            ],
        ],
        [
            'id' => 'sleep',
            'title' => 'Spánok',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'sleep.problemExists', 'label' => 'Spánok – pobem'],
                ['id' => 'sleep.findings', 'label' => 'Zistenia'],
                ['id' => 'sleep.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'mobility',
            'title' => 'Mobilita',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'mobility.level', 'label' => 'Úroveň mobility'],
                ['id' => 'mobility.compensatoryAids', 'label' => 'Kompenzačné pomôcky'],
                ['id' => 'mobility.compensatoryAidsDetails', 'label' => 'Aké kompenzačné pomôcky'],
            ],
        ],
        [
            'id' => 'movement',
            'title' => 'Pohybový systém',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'movement.problemExists', 'label' => 'Pohybový systém – pobem'],
                ['id' => 'movement.findings', 'label' => 'Zistenia'],
                ['id' => 'movement.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'pain',
            'title' => 'Bolesť',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'pain.problemExists', 'label' => 'Bolesť – pobem'],
                ['id' => 'pain.type', 'label' => 'Typ bolesti'],
                ['id' => 'pain.location', 'label' => 'Lokalizácia'],
                ['id' => 'pain.character', 'label' => 'Charakter'],
                ['id' => 'pain.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'nutrition',
            'title' => 'Výživa',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'nutrition.diet', 'label' => 'Diéta č.'],
                ['id' => 'nutrition.weightTrend', 'label' => 'Trend hmotnosti'],
                ['id' => 'nutrition.weightKg', 'label' => 'Hmotnosť (kg)'],
                ['id' => 'nutrition.problemExists', 'label' => 'Výživa – pobem'],
                ['id' => 'nutrition.symptoms', 'label' => 'Symptómy'],
                ['id' => 'nutrition.feedingType', 'label' => 'Typ kŕmenia'],
                ['id' => 'nutrition.preparations', 'label' => 'Prípravky'],
                ['id' => 'nutrition.appetite', 'label' => 'Apetít'],
                ['id' => 'nutrition.intake', 'label' => 'Príjem'],
                ['id' => 'nutrition.gastrostomy', 'label' => 'Gastrostómia'],
                ['id' => 'nutrition.gastrostomyDateIntroduced', 'label' => 'Dátum zavedenia gastrostómie'],
                ['id' => 'nutrition.peg', 'label' => 'PEG'],
                ['id' => 'nutrition.pegDateIntroduced', 'label' => 'Dátum zavedenia PEG'],
                ['id' => 'nutrition.fluidIntake', 'label' => 'Príjem tekutín (ml/24h)'],
                ['id' => 'nutrition.nutritionRoute', 'label' => 'Trasa výživy'],
                ['id' => 'nutrition.cvk', 'label' => 'CVK'],
                ['id' => 'nutrition.cvkDateIntroduced', 'label' => 'Dátum zavedenia CVK'],
                ['id' => 'nutrition.peripheralIVAccess', 'label' => 'Periférny IV prístup'],
                ['id' => 'nutrition.peripheralIVAccessDateIntroduced', 'label' => 'Dátum zavedenia periférneho IV prístupu'],
                ['id' => 'nutrition.denture', 'label' => 'Zubná protéza'],
                ['id' => 'nutrition.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'elimination',
            'title' => 'Vylučovanie',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'defecation.problemExists', 'label' => 'Defekácia – pobem'],
                ['id' => 'defecation.symptoms', 'label' => 'Symptómy defekácie'],
                ['id' => 'defecation.stomaCare', 'label' => 'Starostlivosť o stómiu'],
                ['id' => 'defecation.stomaCareDate', 'label' => 'Dátum zavedenia stómie'],
                ['id' => 'defecation.otherNotes', 'label' => 'Iné zistenia'],
                ['id' => 'defecation.stomaAssistanceNeeded', 'label' => 'Potreba pomoci pri ošetrovaní stómie'],
                ['id' => 'defecation.regulationUsed', 'label' => 'Regulácia vyprázdňovania'],
                ['id' => 'defecation.regulationMethods', 'label' => 'Spôsoby regulácie'],
                ['id' => 'defecation.regulationOtherNotes', 'label' => 'Iné zistenia regulácie'],
                ['id' => 'urination.diuresis', 'label' => 'Diuréza (ml/24 hod.)'],
                ['id' => 'urination.problemExists', 'label' => 'Močenie – pobem'],
                ['id' => 'urination.symptoms', 'label' => 'Symptómy močenia'],
                ['id' => 'urination.catheter', 'label' => 'Permanentný katéter'],
                ['id' => 'urination.catheterDate', 'label' => 'Dátum zavedenia katétra'],
                ['id' => 'urination.urineColor', 'label' => 'Farba moču'],
                ['id' => 'urination.urostomy', 'label' => 'Urostómia'],
                ['id' => 'urination.urostomyDate', 'label' => 'Dátum zavedenia urostómie'],
                ['id' => 'urination.dialysis', 'label' => 'Dialýza'],
                ['id' => 'urination.dialysisDate', 'label' => 'Dátum zavedenia dialýzy'],
                ['id' => 'urination.condomSystem', 'label' => 'Kondómový systém'],
                ['id' => 'urination.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'communication',
            'title' => 'Komunikácia',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'communication.type', 'label' => 'Spôsob komunikácie'],
                ['id' => 'communication.problemExists', 'label' => 'Komunikácia – pobem'],
                ['id' => 'communication.issues', 'label' => 'Pobemy v komunikácii'],
                ['id' => 'communication.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'skin',
            'title' => 'Koža / Edémy / Sliznice / Hygiena',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'skin.problemExists', 'label' => 'Koža – pobem'],
                ['id' => 'skin.temperature', 'label' => 'Teplota kože'],
                ['id' => 'skin.moisture', 'label' => 'Vlhkosť kože'],
                ['id' => 'skin.color', 'label' => 'Farba'],
                ['id' => 'skin.turgor', 'label' => 'Turgor'],
                ['id' => 'skin.integrity', 'label' => 'Celistvosť kože'],
                ['id' => 'skin.changes', 'label' => 'Zmeny na koži'],
                ['id' => 'skin.defectLocation', 'label' => 'Lokalizácia defektu'],
                ['id' => 'skin.defectSizeCm', 'label' => 'Veľkosť defektu (cm)'],
                ['id' => 'skin.patientDayAfterSurgery', 'label' => 'Deň po operácii'],
                ['id' => 'edema.problemExists', 'label' => 'Edémy – pobem'],
                ['id' => 'edema.type', 'label' => 'Typ edému'],
                ['id' => 'edema.measures', 'label' => 'Opatrenia'],
                ['id' => 'mucosa.problemExists', 'label' => 'Sliznice – pobem'],
                ['id' => 'mucosa.findings', 'label' => 'Zistenia na sliznici'],
                ['id' => 'hygiene.statusOnAdmission', 'label' => 'Hygienický stav pri prijatí'],
                ['id' => 'hygiene.selfCare', 'label' => 'Hygienu vykonáva'],
                ['id' => 'skinMucosa.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'postpartum',
            'title' => 'Pôrodné posúdenie (šestonedelie)',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'postpartum.parity', 'label' => 'Poradie pôrodu'],
                ['id' => 'postpartum.deliveryDate', 'label' => 'Dátum pôrodu'],
                ['id' => 'postpartum.deliveryType', 'label' => 'Typ pôrodu'],
                ['id' => 'postpartum.complications', 'label' => 'Komplikácie'],
                ['id' => 'postpartum.complicationDetails', 'label' => 'Podrobnosti komplikácií'],
                ['id' => 'postpartum.fundusUteri', 'label' => 'Fundus maternice'],
                ['id' => 'postpartum.lochiaAppearance', 'label' => 'Vzhľad lochií'],
                ['id' => 'postpartum.lochiaAmount', 'label' => 'Množstvo lochií'],
                ['id' => 'postpartum.woundHealing', 'label' => 'Hojenie poranenia'],
                ['id' => 'postpartum.breasts', 'label' => 'Prsníky'],
                ['id' => 'postpartum.lactation', 'label' => 'Laktácia'],
                ['id' => 'postpartum.newbornSex', 'label' => 'Pohlavie novorodenca'],
                ['id' => 'postpartum.newbornWeight', 'label' => 'Pôrodná hmotnosť (g)'],
                ['id' => 'postpartum.newbornLength', 'label' => 'Dĺžka (cm)'],
                ['id' => 'postpartum.newbornHeadCircumference', 'label' => 'Obvod hlavy (cm)'],
                ['id' => 'postpartum.newbornChestCircumference', 'label' => 'Obvod hrudníka (cm)'],
                ['id' => 'postpartum.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'learning',
            'title' => 'Učenie, zmyslové vnímanie',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'learning.problemExists', 'label' => 'Pobem s učením/zmyslami'],
                ['id' => 'learning.sensoryChanges', 'label' => 'Zmeny v zmysloch'],
                ['id' => 'learning.sensoryChangesExist', 'label' => 'Zmeny prítomné'],
                ['id' => 'learning.sensoryChangesDetails', 'label' => 'Detaily zmien'],
                ['id' => 'learning.compensatoryAids', 'label' => 'Kompenzačné pomôcky'],
                ['id' => 'learning.diseaseKnowledge', 'label' => 'Vedomosti o chorobe'],
                ['id' => 'learning.educationTopics', 'label' => 'Edukačné témy'],
                ['id' => 'learning.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'psychosocial',
            'title' => 'Psychické, sociálne a duchovné potreby',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'psychological.problemExists', 'label' => 'Psychické potreby – pobem'],
                ['id' => 'psychological.mood', 'label' => 'Nálada'],
                ['id' => 'psychological.feelings', 'label' => 'Pocity'],
                ['id' => 'social.problemExists', 'label' => 'Sociálne potreby – pobem'],
                ['id' => 'social.supportDependency', 'label' => 'Sociálna pomoc'],
                ['id' => 'spiritual.problemExists', 'label' => 'Duchovné potreby – pobem'],
                ['id' => 'psychosocial.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'careDeficits',
            'title' => 'Nedostatočnosť v oblasti',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'deficits.areas', 'label' => 'Oblasti nedostatočnosti'],
                ['id' => 'deficits.treatments', 'label' => 'Liečba a intervencie'],
                ['id' => 'deficits.nursingCare', 'label' => 'Ošetrovateľská starostlivosť'],
                ['id' => 'careDeficits.otherNotes', 'label' => 'Iné zistenia'],
            ],
        ],
        [
            'id' => 'patientInstruction',
            'title' => 'Poučenie pacienta/pacientky',
            'layout' => 'compact',
            'fields' => [
                ['id' => 'instruction.topics', 'label' => 'Témy poučenia'],
                ['id' => 'instruction.handoverOnAdmission', 'label' => 'Odovzdané pri prijatí'],
                ['id' => 'instruction.date', 'label' => 'Dátum'],
            ],
        ],
        [
            'id' => 'nursingDiagnoses',
            'title' => 'Stanovenie sesterských diagnóz pri príjme',
            'layout' => 'full',
            'fields' => [
                ['id' => 'nursingDiagnoses.list', 'label' => 'Sesterské diagnózy pri príjme'],
                ['id' => 'nursingDiagnoses.dateTime', 'label' => 'Dátum'],
            ],
        ],
    ],
];
