<?php

namespace Database\Seeders\Demo;

use App\Models\Diagnosis;
use Illuminate\Database\Seeder;

class DiagnosisSeeder extends Seeder
{
    public function run(): void
    {
        if (!env('SEED_SAMPLE_DATA', false)) {
            // no diagnoses generated by default
            return;
        }

        // demo: generate some random diagnoses so UI has data
        for ($i = 0; $i < 30; $i++) {
            $attrs = Diagnosis::factory()->make()->toArray();
            \App\Models\Diagnosis::firstOrCreate(
                ['code' => $attrs['code']],
                $attrs
            );
        }
    }
}
