services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: histomap
      POSTGRES_PASSWORD: histomap_password
      POSTGRES_DB: histomap_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  ors:
    image: openrouteservice/openrouteservice:v8.0.0
    ports:
      - "8080:8082"
    volumes:
      - ./data/ors:/home/ors
    environment:
      REBUILD_GRAPHS: True
      XMS: 1g
      XMX: 2g
      ors.engine.source_file: /home/ors/files/slovakia-251030.osm.pbf
      ors.engine.profiles.car.enabled: true

