/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdoButton: typeof import('./components/ado/AdoButton.vue')['default']
    AdoInput: typeof import('./components/ado/AdoInput.vue')['default']
    AdoSearch: typeof import('./components/ado/AdoSearch.vue')['default']
    AdoTable: typeof import('./components/ado/AdoTable.vue')['default']
    AdoTag: typeof import('./components/ado/AdoTag.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    LogoutButton: typeof import('./components/LogoutButton.vue')['default']
    MenuDropdown: typeof import('./components/MenuDropdown.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UiButton: typeof import('./components/ui/UiButton.vue')['default']
    UiInput: typeof import('./components/ui/UiInput.vue')['default']
    UiSearch: typeof import('./components/ui/UiSearch.vue')['default']
    UiTag: typeof import('./components/ui/UiTag.vue')['default']
  }
}
