<?php

namespace Database\Seeders\Static;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afganistan', 'code' => 'AF'],
            ['name' => 'Albánsko', 'code' => 'AL'],
            ['name' => 'Antarktída', 'code' => 'AQ'],
            ['name' => 'Alžírsko', 'code' => 'DZ'],
            ['name' => 'Americká Samoa', 'code' => 'AS'],
            ['name' => 'Andorra', 'code' => 'AD'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Antigua a Barbuda', 'code' => 'AG'],
            ['name' => 'Azerbajdžan', 'code' => 'AZ'],
            ['name' => 'Argentína', 'code' => 'AR'],
            ['name' => 'Austrália', 'code' => 'AU'],
            ['name' => 'Rakúsko', 'code' => 'AT'],
            ['name' => 'Bahamy', 'code' => 'BS'],
            ['name' => 'Bahrajn', 'code' => 'BH'],
            ['name' => 'Bangladéš', 'code' => 'BD'],
            ['name' => 'Arménsko', 'code' => 'AM'],
            ['name' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Belgicko', 'code' => 'BE'],
            ['name' => 'Bermudy', 'code' => 'BM'],
            ['name' => 'Bhután', 'code' => 'BT'],
            ['name' => 'Bolívia', 'code' => 'BO'],
            ['name' => 'Bosna a Hercegovina', 'code' => 'BA'],
            ['name' => 'Botswana', 'code' => 'BW'],
            ['name' => 'Bouvetov ostrov', 'code' => 'BV'],
            ['name' => 'Brazília', 'code' => 'BR'],
            ['name' => 'Belize', 'code' => 'BZ'],
            ['name' => 'Brit.indickooceán.územie', 'code' => 'IO'],
            ['name' => 'Šalamúnove ostrovy', 'code' => 'SB'],
            ['name' => 'Britské Panenské ostr.', 'code' => 'VG'],
            ['name' => 'Brunej', 'code' => 'BN'],
            ['name' => 'Bulharsko', 'code' => 'BG'],
            ['name' => 'Mjanmarsko', 'code' => 'MM'],
            ['name' => 'Burundi', 'code' => 'BI'],
            ['name' => 'Bielorusko', 'code' => 'BY'],
            ['name' => 'Kambodža', 'code' => 'KH'],
            ['name' => 'Kamerun', 'code' => 'CM'],
            ['name' => 'Kanada', 'code' => 'CA'],
            ['name' => 'Kapverdy', 'code' => 'CV'],
            ['name' => 'Kajmanie ostrovy', 'code' => 'KY'],
            ['name' => 'Stredoafrická republika', 'code' => 'CF'],
            ['name' => 'Srí Lanka', 'code' => 'LK'],
            ['name' => 'Čad', 'code' => 'TD'],
            ['name' => 'Čile', 'code' => 'CL'],
            ['name' => 'Čína', 'code' => 'CN'],
            ['name' => 'Taiwan', 'code' => 'TW'],
            ['name' => 'Vianočný ostrov', 'code' => 'CX'],
            ['name' => 'Kokosové ostrovy', 'code' => 'CC'],
            ['name' => 'Kolumbia', 'code' => 'CO'],
            ['name' => 'Komory', 'code' => 'KM'],
            ['name' => 'Mayotte', 'code' => 'YT'],
            ['name' => 'Kongo', 'code' => 'CG'],
            ['name' => 'Kongo (býv. Zair)', 'code' => 'CD'],
            ['name' => 'Cookove ostrovy', 'code' => 'CK'],
            ['name' => 'Kostarika', 'code' => 'CR'],
            ['name' => 'Chorvátsko', 'code' => 'HR'],
            ['name' => 'Kuba', 'code' => 'CU'],
            ['name' => 'Cyprus', 'code' => 'CY'],
            ['name' => 'Československo', 'code' => 'CS'],
            ['name' => 'Česko', 'code' => 'CZ'],
            ['name' => 'Benin', 'code' => 'BJ'],
            ['name' => 'Dánsko', 'code' => 'DK'],
            ['name' => 'Dominika', 'code' => 'DM'],
            ['name' => 'Dominikánska republika', 'code' => 'DO'],
            ['name' => 'Ekvádor', 'code' => 'EC'],
            ['name' => 'Salvádor', 'code' => 'SV'],
            ['name' => 'Rovníková Guinea', 'code' => 'GQ'],
            ['name' => 'Etiópia', 'code' => 'ET'],
            ['name' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Estónsko', 'code' => 'EE'],
            ['name' => 'Faerské ostrovy', 'code' => 'FO'],
            ['name' => 'Falklandy', 'code' => 'FK'],
            ['name' => 'Juž. Georgia a J.S.o.', 'code' => 'GS'],
            ['name' => 'Fidži', 'code' => 'FJ'],
            ['name' => 'Fínsko', 'code' => 'FI'],
            ['name' => 'Alandy', 'code' => 'AX'],
            ['name' => 'Metropolitné Francúzsko', 'code' => 'FX'],
            ['name' => 'Francúzsko', 'code' => 'FR'],
            ['name' => 'Francúzska Guyana', 'code' => 'GF'],
            ['name' => 'Francúzska Polynézia', 'code' => 'PF'],
            ['name' => 'Francúzske južné územia', 'code' => 'TF'],
            ['name' => 'Džibutsko', 'code' => 'DJ'],
            ['name' => 'Gabon', 'code' => 'GA'],
            ['name' => 'Gruzínsko', 'code' => 'GE'],
            ['name' => 'Gambia', 'code' => 'GM'],
            ['name' => 'Palestína', 'code' => 'PS'],
            ['name' => 'Nemecko', 'code' => 'DE'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Gibraltár', 'code' => 'GI'],
            ['name' => 'Kiribati', 'code' => 'KI'],
            ['name' => 'Grécko', 'code' => 'GR'],
            ['name' => 'Grónsko', 'code' => 'GL'],
            ['name' => 'Grenada', 'code' => 'GD'],
            ['name' => 'Guadeloupe', 'code' => 'GP'],
            ['name' => 'Guam', 'code' => 'GU'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Guinea', 'code' => 'GN'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Haiti', 'code' => 'HT'],
            ['name' => 'Heard.ostr.a Macd.ostr.', 'code' => 'HM'],
            ['name' => 'Vatikán', 'code' => 'VA'],
            ['name' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Hongkong', 'code' => 'HK'],
            ['name' => 'Maďarsko', 'code' => 'HU'],
            ['name' => 'Island', 'code' => 'IS'],
            ['name' => 'India', 'code' => 'IN'],
            ['name' => 'Indonézia', 'code' => 'ID'],
            ['name' => 'Irán', 'code' => 'IR'],
            ['name' => 'Irak', 'code' => 'IQ'],
            ['name' => 'Írsko', 'code' => 'IE'],
            ['name' => 'Izrael', 'code' => 'IL'],
            ['name' => 'Taliansko', 'code' => 'IT'],
            ['name' => 'Pobrežie slonoviny', 'code' => 'CI'],
            ['name' => 'Jamajka', 'code' => 'JM'],
            ['name' => 'Japonsko', 'code' => 'JP'],
            ['name' => 'Kazachstan', 'code' => 'KZ'],
            ['name' => 'Jordánsko', 'code' => 'JO'],
            ['name' => 'Keňa', 'code' => 'KE'],
            ['name' => 'Kórej.ľudovodem.rep.', 'code' => 'KP'],
            ['name' => 'Kórejská republika', 'code' => 'KR'],
            ['name' => 'Kuvajt', 'code' => 'KW'],
            ['name' => 'Kirgizsko', 'code' => 'KG'],
            ['name' => 'Laos', 'code' => 'LA'],
            ['name' => 'Libanon', 'code' => 'LB'],
            ['name' => 'Lesotho', 'code' => 'LS'],
            ['name' => 'Lotyšsko', 'code' => 'LV'],
            ['name' => 'Libéria', 'code' => 'LR'],
            ['name' => 'Líbya', 'code' => 'LY'],
            ['name' => 'Lichtenštajnsko', 'code' => 'LI'],
            ['name' => 'Litva', 'code' => 'LT'],
            ['name' => 'Luxembursko', 'code' => 'LU'],
            ['name' => 'Macao', 'code' => 'MO'],
            ['name' => 'Madagaskar', 'code' => 'MG'],
            ['name' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Malajzia', 'code' => 'MY'],
            ['name' => 'Maldivy', 'code' => 'MV'],
            ['name' => 'Mali', 'code' => 'ML'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Martinik', 'code' => 'MQ'],
            ['name' => 'Mauritánia', 'code' => 'MR'],
            ['name' => 'Maurícius', 'code' => 'MU'],
            ['name' => 'Mexiko', 'code' => 'MX'],
            ['name' => 'Monako', 'code' => 'MC'],
            ['name' => 'Mongolsko', 'code' => 'MN'],
            ['name' => 'Moldavsko', 'code' => 'MD'],
            ['name' => 'Čierna Hora', 'code' => 'ME'],
            ['name' => 'Montserrat', 'code' => 'MS'],
            ['name' => 'Maroko', 'code' => 'MA'],
            ['name' => 'Mozambik', 'code' => 'MZ'],
            ['name' => 'Omán', 'code' => 'OM'],
            ['name' => 'Namíbia', 'code' => 'NA'],
            ['name' => 'Nauru', 'code' => 'NR'],
            ['name' => 'Nepál', 'code' => 'NP'],
            ['name' => 'Holandsko', 'code' => 'NL'],
            ['name' => 'Holandské Antily', 'code' => 'AN'],
            ['name' => 'Curaçao', 'code' => 'CW'],
            ['name' => 'Aruba', 'code' => 'AW'],
            ['name' => 'Svätý Martin (holand.č.)', 'code' => 'SX'],
            ['name' => 'Bonaire,Sv.Eustach,Saba', 'code' => 'BQ'],
            ['name' => 'Neutrálne územia', 'code' => 'NT'],
            ['name' => 'Nová Kaledónia', 'code' => 'NC'],
            ['name' => 'Vanuatu', 'code' => 'VU'],
            ['name' => 'Nový Zéland', 'code' => 'NZ'],
            ['name' => 'Nikaragua', 'code' => 'NI'],
            ['name' => 'Niger', 'code' => 'NE'],
            ['name' => 'Nigéria', 'code' => 'NG'],
            ['name' => 'Niue', 'code' => 'NU'],
            ['name' => 'Norfolk', 'code' => 'NF'],
            ['name' => 'Nórsko', 'code' => 'NO'],
            ['name' => 'Severné Mariány', 'code' => 'MP'],
            ['name' => 'Menšie odľahlé ostr.USA', 'code' => 'UM'],
            ['name' => 'Mikronézia', 'code' => 'FM'],
            ['name' => 'Marshallove ostrovy', 'code' => 'MH'],
            ['name' => 'Palau', 'code' => 'PW'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Panama', 'code' => 'PA'],
            ['name' => 'Papua-Nová Guinea', 'code' => 'PG'],
            ['name' => 'Paraguaj', 'code' => 'PY'],
            ['name' => 'Peru', 'code' => 'PE'],
            ['name' => 'Filipíny', 'code' => 'PH'],
            ['name' => 'Pitcairnove ostrovy', 'code' => 'PN'],
            ['name' => 'Poľsko', 'code' => 'PL'],
            ['name' => 'Portugalsko', 'code' => 'PT'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW'],
            ['name' => 'Východný Timor', 'code' => 'TL'],
            ['name' => 'Portoriko', 'code' => 'PR'],
            ['name' => 'Katar', 'code' => 'QA'],
            ['name' => 'Réunion', 'code' => 'RE'],
            ['name' => 'Rumunsko', 'code' => 'RO'],
            ['name' => 'Rusko', 'code' => 'RU'],
            ['name' => 'Rwanda', 'code' => 'RW'],
            ['name' => 'Svätý Bartolomej', 'code' => 'BL'],
            ['name' => 'Sv.Helena,Asc,Trist.daC.', 'code' => 'SH'],
            ['name' => 'Svätý Krištof a Nevis', 'code' => 'KN'],
            ['name' => 'Anguilla', 'code' => 'AI'],
            ['name' => 'Svätá Lucia', 'code' => 'LC'],
            ['name' => 'Svätý Martin (franc.č.)', 'code' => 'MF'],
            ['name' => 'Saint Pierre a Miquelon', 'code' => 'PM'],
            ['name' => 'Sv. Vincent a Grenadíny', 'code' => 'VC'],
            ['name' => 'San Maríno', 'code' => 'SM'],
            ['name' => 'Sv. Tomáš a Princov ost.', 'code' => 'ST'],
            ['name' => 'Saudská Arábia', 'code' => 'SA'],
            ['name' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Srbsko', 'code' => 'RS'],
            ['name' => 'Seychely', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Singapur', 'code' => 'SG'],
            ['name' => 'Slovensko', 'code' => 'SK'],
            ['name' => 'Vietnam', 'code' => 'VN'],
            ['name' => 'Slovinsko', 'code' => 'SI'],
            ['name' => 'Somálsko', 'code' => 'SO'],
            ['name' => 'Južná Afrika', 'code' => 'ZA'],
            ['name' => 'Zimbabwe', 'code' => 'ZW'],
            ['name' => 'Španielsko', 'code' => 'ES'],
            ['name' => 'Južný Sudán', 'code' => 'SS'],
            ['name' => 'Sudán', 'code' => 'SD'],
            ['name' => 'Západná Sahara', 'code' => 'EH'],
            ['name' => 'Surinam', 'code' => 'SR'],
            ['name' => 'Svalbard a Jan Mayen', 'code' => 'SJ'],
            ['name' => 'Eswatini', 'code' => 'SZ'],
            ['name' => 'Švédsko', 'code' => 'SE'],
            ['name' => 'Švajčiarsko', 'code' => 'CH'],
            ['name' => 'Sýria', 'code' => 'SY'],
            ['name' => 'Tadžikistan', 'code' => 'TJ'],
            ['name' => 'Thajsko', 'code' => 'TH'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Tokelau', 'code' => 'TK'],
            ['name' => 'Tonga', 'code' => 'TO'],
            ['name' => 'Trinidad a Tobago', 'code' => 'TT'],
            ['name' => 'Spojené arabské emiráty', 'code' => 'AE'],
            ['name' => 'Tunisko', 'code' => 'TN'],
            ['name' => 'Turecko', 'code' => 'TR'],
            ['name' => 'Turkménsko', 'code' => 'TM'],
            ['name' => 'Turks a Caicos', 'code' => 'TC'],
            ['name' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ukrajina', 'code' => 'UA'],
            ['name' => 'Severné Macedónsko', 'code' => 'MK'],
            ['name' => 'Spol.nezávislých štátov', 'code' => 'SU'],
            ['name' => 'Egypt', 'code' => 'EG'],
            ['name' => 'Spojené kráľovstvo', 'code' => 'GB'],
            ['name' => 'Guernsey', 'code' => 'GG'],
            ['name' => 'Jersey', 'code' => 'JE'],
            ['name' => 'Man', 'code' => 'IM'],
            ['name' => 'Tanzánia', 'code' => 'TZ'],
            ['name' => 'Spojené štáty, USA', 'code' => 'US'],
            ['name' => 'Americké Panenské ostr.', 'code' => 'VI'],
            ['name' => 'Burkina', 'code' => 'BF'],
            ['name' => 'Uruguaj', 'code' => 'UY'],
            ['name' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Venezuela', 'code' => 'VE'],
            ['name' => 'Wallis a Futuna', 'code' => 'WF'],
            ['name' => 'Samoa', 'code' => 'WS'],
            ['name' => 'Jemen', 'code' => 'YE'],
            ['name' => 'Srbsko a Čierna Hora', 'code' => 'CS'],
            ['name' => 'Zambia', 'code' => 'ZM'],
            ['name' => 'Macedónsko', 'code' => 'XC'],
        ];

        foreach ($countries as $country) {
            Country::firstOrCreate(
                ['code' => $country['code']],
                ['name' => $country['name']]
            );
        }
    }
}
