version: '3.8'

services:
  ors:
    image: openrouteservice/openrouteservice:v8.0.0
    ports:
      - "8080:8082"
    volumes:
      - ./ors-docker:/home/ors
    environment:
      REBUILD_GRAPHS: True
      XMS: 1g
      XMX: 2g
      ors.engine.source_file: /home/ors/files/slovakia-251030.osm.pbf
      ors.engine.profiles.car.enabled: true
